@RUTA
@REMOLQUE
@CAMION
@CIUDAD
@CARRETERA
@MOVIMIENTO
@CONDUCTOR
@PAGO
@INGRESO
@PEDIDO
@PARQUE
@LINEA
@TRAMO
@RUT_TRA
@REM_PAR
@CAM_REM
@CAMIONPROPIO
@CON_CAM
ALTER TABLE INGRESO
ADD CONSTRAINT ca_ingreso_pedido FOREIGN KEY (NUM_PEDIDO) REFERENCES PEDIDO (NUM_PEDIDO);